### Get application info
GET http://localhost:{{port}}/application-info

### Get application info for two services
GET http://localhost:{{port}}/application-info?requestTo={{requestTo}}

### Get logo
GET http://localhost:{{port}}/application-info/logo