### Get application info
GET http://localhost:{{port}}/application-info

### Get extended application info
GET http://localhost:{{port}}/application-info?projection=FULL

### Get logo
GET http://localhost:{{port}}/application-info/logo